services:
  db:
    image: postgres:15
    container_name: f1sim-db
    environment:
      POSTGRES_DB: f1sim
      POSTGRES_USER: f1sim
      POSTGRES_PASSWORD: f1sim
    ports:
      - "5435:5432"
    volumes:
      - f1sim-db-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: f1sim-redis
    ports:
      - "6381:6379"

  backend:
    build: ./backend
    container_name: f1sim-backend
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/f1sim
      DB_USERNAME: f1sim
      DB_PASSWORD: f1sim
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8090:8090"

volumes:
  f1sim-db-data: